// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PMHUB.Infrastructure.Persistence;

#nullable disable

namespace PMHUB.Infrastructure.Migrations
{
    [DbContext(typeof(PMHubDbContext))]
    [Migration("20260622120000_AddHeaderNotificationStates")]
    partial class AddHeaderNotificationStates
    {
    }
}
