// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PMHUB.Infrastructure.Persistence;

#nullable disable

namespace PMHUB.Infrastructure.Migrations
{
    [DbContext(typeof(PMHubDbContext))]
    [Migration("20260609102000_AddTargetSettings")]
    partial class AddTargetSettings
    {
    }
}
